### ISSUE TITLE
Server crash at start

### ISSUE THREAD

**Issue by H4Mm3r** [MrCrayfish/Filters#9]
Forge version 28.2.3
Filters version : 1.1.1

[11:44:31] [Server thread/FATAL] [ne.mi.fm.ModLoader/LOADING]: Failed to complete lifecycle event CONSTRUCT, 1 errors found
[11:44:31] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
        Filters (filters) has failed to load correctly
§7net/minecraft/client/gui/widget/button/Button
]
        at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:201) ~[?:?] {re:classloading}
        at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:183) ~[?:?] {re:classloading}
        at net.minecraftforge.fml.server.ServerModLoader.begin(ServerModLoader.java:45) ~[?:?] {re:classloading}
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:121) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:598) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212] {}
[11:44:31] [Server thread/ERROR] [minecraft/MinecraftServer]: This crash report has been saved to: /opt/minecraft_server_new/./crash-reports/crash-2020-04-12_11.44.31-server.txt
[11:44:31] [Server thread/INFO] [minecraft/MinecraftServer]: Stopping server
[11:44:31] [Server thread/INFO] [minecraft/MinecraftServer]: Saving worlds
[11:44:31] [Server thread/ERROR] [minecraft/MinecraftServer]: Exception stopping the server
java.lang.RuntimeException: The server has failed to initialize correctly due to mod loading errors. Examine the crash report for more details.
        at net.minecraftforge.common.DimensionManager.getWorld(DimensionManager.java:182) ~[?:?] {re:classloading}
        at net.minecraft.server.MinecraftServer.func_71218_a(MinecraftServer.java:979) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_213211_a(MinecraftServer.java:521) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:553) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.dedicated.DedicatedServer.func_71260_j(DedicatedServer.java:544) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:661) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212] {}

Server is not starting.

**Comment by MrCrayfish** [comment]
Fliters is a client only mod.

**Comment by H4Mm3r** [comment]
Oops, sorry thanks for the answer
